//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitorCheckIn
{
    using System;
    using System.Collections.Generic;
    
    public partial class visitor
    {
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string company { get; set; }
        public string visiting { get; set; }
        public string idtype { get; set; }
        public int visitorId { get; set; }
        public string vehiclenum { get; set; }
        public string contactnum { get; set; }
        public string purpose { get; set; }
        public string status { get; set; }
        public System.DateTime checkin { get; set; }
        public System.DateTime checkout { get; set; }
    }
}
